### ISSUE TITLE
⏱ Parsing time from ISO standard to human readable.

### ISSUE THREAD

**Issue by evilghostgirl** [evilghostgirl/locally-frontend-web#12]
Add moment.js or another lib for dealing with timestamps and parse {offer.added_at} in the offers-panel/OfferCard.js.
Example:
from:  "added_at": "2019-12-27T07:45:00Z", 
to: 7:45, 27 dec
or another human format that will look nice

**Comment by TomaszKisiel** [comment]
DONE
