### ISSUE TITLE
Will there be more carrots in the project?

### ISSUE THREAD

**Issue by TomaszKisiel** [evilghostgirl/locally-frontend-web#6]
### **WELL?**
In my opinion it's not that good or not good. If I were to say what I value most in life, I would say people. Ekhm ... People who gave me a helping hand when I could not cope, when I was alone. And what's interesting, it is the chance meetings that affect our lives. The point is that when you confess certain values, even seemingly universal, it happens that there is no understanding, so to speak, that helps us develop. I was lucky to say that because I found them. And thank you life. Thank him, life is singing, life is dance, life is love. Many people ask me the same, but how do you do it? Where do you get this joy from? And I answer that it's simple, it's a love of life, it is today that makes me build machines today, and tomorrow ... who knows why not, I will devote myself to social work and I will be, even planting ... means ... **carrots**.

**Comment by TomaszKisiel** [comment]
Nkdayzdcznr silyczrsrndi.
_GA-DE-RY-PO-LU-KI_

**Comment by evilghostgirl** [comment]
XDDX
